Validate and add Docker v24.0.3 to v24.0.7
rancher/install-docker pull request #123
Opened 2023-11-07 05:25 UTC by chiukapoor

### Updates
* Added the following docker versions:
```
24.0.3
24.0.4
24.0.5
24.0.6
24.0.7
```
### Testing
* `make test` Passed
### Relevant Issue
* Fixes https://github.com/rancher/rancher/issues/43362

2023-11-17 20:53 UTC, snasovich requested changes
Ubuntu 22.04 test is skipped for Docker 24.0.x due to typo in regex - https://github.com/rancher/install-docker/pull/116/files#diff-1f19504f50a28b7ce80f9bf28a30c0bcb2062d38ecdbfc1f9590848a117c66feR18 (should be `^24.0` instead of `^24.0]`).

Looks like we actually have an issue with that script per https://github.com/rancher/terraform-provider-rancher2/issues/1215 - Docker 24.0 install script is failing on Ubuntu 22.04.

Could you please fix the `test-docker` file and see if our test passes?

2023-11-23 18:41 UTC, chiukapoor commented
- Fixed the typo in regex
- Test is passing for Docker 24.0.x on Ubuntu 
```
[PASS] ubuntu:22.04-24.0.7 exit code: 0
[PASS] ubuntu:22.04-24.0.6 exit code: 0
[PASS] ubuntu:22.04-24.0.5 exit code: 0
[PASS] ubuntu:22.04-24.0.4 exit code: 0
[PASS] ubuntu:22.04-24.0.3 exit code: 0
[PASS] ubuntu:22.04-24.0.2 exit code: 0
[PASS] ubuntu:22.04-24.0.1 exit code: 0
[PASS] ubuntu:22.04-24.0.0 exit code: 0
```

2023-11-27 15:08 UTC, snasovich approved these changes
LGTM. @kinarashah , please review as well. After Kinara's approval, please merge.

2023-12-12 02:41 UTC, kinarashah approved these changes

2023-12-13 15:42 UTC, merged