add special case for redhatenterprise
rancher/install-docker pull request #81
Opened 2021-08-05 06:02 UTC by xibuka

In RHEL 8.x lsb_release will return `redhatenterprise`, which is not mentioned in the script.

2021-08-05 09:03 UTC, superseb requested changes
Please create an issue and mention the issue in the PR, also change 19.03.13 and 19.03.14 as those are the versions released for EL8.

2021-08-06 05:00 UTC, xibuka commented
Created Issue https://github.com/rancher/rancher/issues/34007 and also fixed `19.03.13` and `19.03.14` in this PR.

2021-08-06 05:21 UTC, superseb commented
@xibuka Please squash commits to 1 and re-request review after so I get notified

2021-08-10 01:11 UTC, xibuka commented
I will cancel this PR and create a new one to merge all 3 commits into 1.

2021-08-10 01:11 UTC, closed without merging